// Code generated by "enumer -type=Kind --linecomment"; DO NOT EDIT.

package main

import (
	"fmt"
	"strings"
)

const _KindName = "FNRLSEWShipWP"

var _KindIndex = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7, 11, 13}

const _KindLowerName = "fnrlsewshipwp"

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_KindIndex)-1) {
		return fmt.Sprintf("Kind(%d)", i)
	}
	return _KindName[_KindIndex[i]:_KindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _KindNoOp() {
	var x [1]struct{}
	_ = x[KindF-(0)]
	_ = x[KindN-(1)]
	_ = x[KindR-(2)]
	_ = x[KindL-(3)]
	_ = x[KindS-(4)]
	_ = x[KindE-(5)]
	_ = x[KindW-(6)]
	_ = x[KindShip-(7)]
	_ = x[KindWP-(8)]
}

var _KindValues = []Kind{KindF, KindN, KindR, KindL, KindS, KindE, KindW, KindShip, KindWP}

var _KindNameToValueMap = map[string]Kind{
	_KindName[0:1]:        KindF,
	_KindLowerName[0:1]:   KindF,
	_KindName[1:2]:        KindN,
	_KindLowerName[1:2]:   KindN,
	_KindName[2:3]:        KindR,
	_KindLowerName[2:3]:   KindR,
	_KindName[3:4]:        KindL,
	_KindLowerName[3:4]:   KindL,
	_KindName[4:5]:        KindS,
	_KindLowerName[4:5]:   KindS,
	_KindName[5:6]:        KindE,
	_KindLowerName[5:6]:   KindE,
	_KindName[6:7]:        KindW,
	_KindLowerName[6:7]:   KindW,
	_KindName[7:11]:       KindShip,
	_KindLowerName[7:11]:  KindShip,
	_KindName[11:13]:      KindWP,
	_KindLowerName[11:13]: KindWP,
}

var _KindNames = []string{
	_KindName[0:1],
	_KindName[1:2],
	_KindName[2:3],
	_KindName[3:4],
	_KindName[4:5],
	_KindName[5:6],
	_KindName[6:7],
	_KindName[7:11],
	_KindName[11:13],
}

// KindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func KindString(s string) (Kind, error) {
	if val, ok := _KindNameToValueMap[s]; ok {
		return val, nil
	}
	s = strings.ToLower(s)
	if val, ok := _KindNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Kind values", s)
}

// KindValues returns all values of the enum
func KindValues() []Kind {
	return _KindValues
}

// KindStrings returns a slice of all String values of the enum
func KindStrings() []string {
	strs := make([]string, len(_KindNames))
	copy(strs, _KindNames)
	return strs
}

// IsAKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Kind) IsAKind() bool {
	for _, v := range _KindValues {
		if i == v {
			return true
		}
	}
	return false
}
