// Code generated by "enumer -type=Kind --linecomment"; DO NOT EDIT.

package main

import (
	"fmt"
	"strings"
)

const _KindName = ".#L"

var _KindIndex = [...]uint8{0, 1, 2, 3}

const _KindLowerName = ".#l"

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_KindIndex)-1) {
		return fmt.Sprintf("Kind(%d)", i)
	}
	return _KindName[_KindIndex[i]:_KindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _KindNoOp() {
	var x [1]struct{}
	_ = x[KindFloor-(0)]
	_ = x[KindOccupied-(1)]
	_ = x[KindEmpty-(2)]
}

var _KindValues = []Kind{KindFloor, KindOccupied, KindEmpty}

var _KindNameToValueMap = map[string]Kind{
	_KindName[0:1]:      KindFloor,
	_KindLowerName[0:1]: KindFloor,
	_KindName[1:2]:      KindOccupied,
	_KindLowerName[1:2]: KindOccupied,
	_KindName[2:3]:      KindEmpty,
	_KindLowerName[2:3]: KindEmpty,
}

var _KindNames = []string{
	_KindName[0:1],
	_KindName[1:2],
	_KindName[2:3],
}

// KindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func KindString(s string) (Kind, error) {
	if val, ok := _KindNameToValueMap[s]; ok {
		return val, nil
	}
	s = strings.ToLower(s)
	if val, ok := _KindNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Kind values", s)
}

// KindValues returns all values of the enum
func KindValues() []Kind {
	return _KindValues
}

// KindStrings returns a slice of all String values of the enum
func KindStrings() []string {
	strs := make([]string, len(_KindNames))
	copy(strs, _KindNames)
	return strs
}

// IsAKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Kind) IsAKind() bool {
	for _, v := range _KindValues {
		if i == v {
			return true
		}
	}
	return false
}
